### PR TITLE
Add language packs support

### PR DESCRIPTION
**Pull request by mardy**
This is related to https://github.com/ubports/system-settings/pull/84

### CODE REVIEW

**Comment by mardy** [comment]
This can be tested with one of the clicks at https://ci.ubports.com/job/xenial-rootfs-minimal-armhf/41/artifact/clicks/

**Comment by bhdouglass** [comment]
@mardy I finally got a change to review this, but when I built and installed the deb it reported the language pack click as a pass rather than needing manual review as expected.

**Comment by mardy** [comment]
@bhdouglass true, but if you run it with the `--json` option you'll find that it says:
```
...
  "click,snap.v1_language_packs": {
    "error": {},
    "info": {
      "language_packs:manifest:language-as": {
        "manual_review": true,
        "text": "OK"
      },
      "language_packs:peer_hooks_disallowed:language-packs": {
        "manual_review": false,
        "text": "OK"
      },
      "language_packs:peer_hooks_required:language-packs": {
        "manual_review": false,
        "text": "OK"
      }
    },
    "warn": {}
  },
...
```
Isn't that enough?

**Comment by bhdouglass** [comment]
It should work both ways as to not cause user confusion

**Comment by mardy** [comment]
@bhdouglass, now it should be fixed, please re-check :-)

**Review by bhdouglass — APPROVED** [review]
Looks great!

**Pull request merged**
